version: '3.1'
services:
    mysql:
      image: 'mysql/mysql-server:8.0'
      container_name: mysql
      expose:
       - "3310"
      ports:
        - 3310:3310
      environment:
        MYSQL_ROOT_PASSWORD: 'password'
        MYSQL_ROOT_HOST: '%'
        MYSQL_DATABASE: 'MasterDaWeb'
        MYSQL_USER: 'masterdaweb'
        MYSQL_PASSWORD: 'secreta'
        MYSQL_ALLOW_EMPTY_PASSWORD: 1
      networks:
        - app-network

    phpmyadmin:
        depends_on:
            - mysql
        image: phpmyadmin/phpmyadmin
        restart: always
        ports: 
            - "8090:80"
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: password
        networks:
            - app-network

    laravel:
        build: ./backend
        container_name: laravel
        ports: 
           - "8000:80"
        volumes:
            - './backend/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
            - './backend:/usr/share/nginx'
        networks:
            - app-network

    composer:
        container_name: composer
        image: composer/composer
        command: install
    
    frontend:
        container_name: frontend
        build: 
            context: ./frontend
            dockerfile: Dockerfile
        command: ["npm", "run", "serve"]
        volumes:
            - ./frontend:/app
            - /app/node_modules # enables a much faster start/reload
        ports:
            - "8080:8080"
        environment: 
            - CHOKIDAR_USEPOLLING=true # enables the hot reloading
        networks:
            - app-network


networks:
  app-network:
    driver: bridge